apiVersion: v1
kind: Service
metadata:
  name: angular-service
  namespace: nourpfe
spec:
  selector:
    app: angular-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
