{{- if and .Values.mysql.persistence.enabled (not .Values.mysql.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: mysql
spec:
  capacity:
    storage: {{ .Values.mysql.persistence.storage }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mysql.persistence.storageClass }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.mysql.persistence.hostPath }}
{{- end }}

