apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-images-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: {{ .Values.nginx.volume.hostPath }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-images-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nginx-images-pv
