apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.angular.name }}-nodeport
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.angular.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.angular.service.port }}
      targetPort: {{ .Values.angular.service.targetPort }}
      nodePort: {{ .Values.angular.service.nodePort }}
  type: {{ .Values.angular.service.type }}


