{{- if .Values.springboot.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.springboot.name }}-servicemonitor
  namespace: {{ .Values.namespace }}
  labels:
    app: spring-boot-app
    release: my-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: spring-boot-app
      monitoring: "true"
  endpoints:
  - port: metrics
    path: {{ .Values.springboot.monitoring.serviceMonitor.path | default "/actuator/prometheus" }}
    interval: 30s
    scrapeTimeout: 10s
{{- end }}
