{{- if .Values.springboot.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-app-servicemonitor
  namespace: {{ .Values.namespace }}
  labels:
    app: spring-boot-app
    release: my-kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: spring-boot-pod
      monitoring: "true"
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s
{{- end }}

