namespace: lassoued

angular:
  name: angular
  image:
    repository: nourlassoued/nourangular
    tag: "1.1.117"
    pullPolicy: Always
  replicaCount: 1
  labels:
    app: angular-pod
    type: angular-monolithique
  containerPort: 80
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  service:
    type: NodePort
    port: 4200
    targetPort: 80
    nodePort: 30800
  apiUrl: "http://192.168.16.140:31000/nour"

mysql:
  name: mysql
  image:
    repository: mysql
    tag: "8.0"
  rootPassword: root
  database: backendnourpfe
  containerPort: 3306
  persistence:
    enabled: true
    storage: 1Gi
    storageClass: standard
    hostPath: /mnt/data/mysql
    existingClaim: ""
  service:
    name: mysql-service
    type: ClusterIP
    port: 3306
    targetPort: 3306

springboot:
  name: spring-boot-app
  image:
    repository: nourlassoued/nourspring
    tag: "1.0.74"
    pullPolicy: Always
  replicaCount: 1
  containerPort: 8088
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  env:
    SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/backendnourpfe?createDatabaseIfNotExist=true"
    SPRING_DATASOURCE_USERNAME: "root"
    SPRING_DATASOURCE_PASSWORD: "root"
    SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  service:
    type: NodePort
    port: 8088
    targetPort: 8088
    nodePort: 31000
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 50
  volume:
    enabled: true
    mountPath: /mnt/data/images
    hostPath: /mnt/data/images
    existingClaim: ""

nginx:
  name: nginx-images
  image:
    repository: nginx
    tag: "latest"
  containerPort: 80
  service:
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 32000
  volume:
    enabled: true
    mountPath: /usr/share/nginx/html/img
    hostPath: /mnt/data/images
    existingClaim: ""
  resources:
    requests:
      memory: "32Mi"
      cpu: "50m"
    limits:
      memory: "64Mi"
      cpu: "100m"
chatbot:
  name: chatbot
  image:
    repository: nourlassoued/chatbot-flask
    tag: "latest"
    pullPolicy: Always
  replicaCount: 1
  containerPort: 5000
  service:
    type: NodePort
    port: 5000
    targetPort: 5000
    nodePort: 31100


